apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../../home/akdc/.ssh/
- pvc.yaml
- cvcapture.yaml
- inference.yaml
- predict.yaml
- rtspsim.yaml
- upload.yaml
- web.yaml
