---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: voe
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/central-tx-elpaso-333/voe
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
